name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from develop branch
        id: check_branch
        run: |
          if [ "${{ github.base_ref }}" == "main" ] && [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Pull requests to main can only come from the develop branch."
            exit 1
          else
            echo "PR is valid."
          fi
